
-- ============================================================
-- Retail360 | PostgreSQL Data Warehouse
-- File: 01_create_retail360_schema.sql
-- Purpose: Create a retail analytics star schema
-- ============================================================

BEGIN;

CREATE SCHEMA IF NOT EXISTS retail360;

SET search_path TO retail360, public;


-- ============================================================
-- 1. DIMENSION: DATE
-- ============================================================

CREATE TABLE IF NOT EXISTS dim_date (
    date_key        INTEGER PRIMARY KEY,
    full_date       DATE NOT NULL UNIQUE,
    day_number      SMALLINT NOT NULL,
    month_number    SMALLINT NOT NULL,
    month_name      VARCHAR(20) NOT NULL,
    quarter_number  SMALLINT NOT NULL,
    year_number     SMALLINT NOT NULL,
    year_month      VARCHAR(7) NOT NULL,
    day_of_week     VARCHAR(20) NOT NULL,
    is_weekend      BOOLEAN NOT NULL,

    CONSTRAINT chk_dim_date_month
        CHECK (month_number BETWEEN 1 AND 12),

    CONSTRAINT chk_dim_date_quarter
        CHECK (quarter_number BETWEEN 1 AND 4)
);


-- ============================================================
-- 2. DIMENSION: CUSTOMER
-- ============================================================

CREATE TABLE IF NOT EXISTS dim_customer (
    customer_key       BIGINT GENERATED BY DEFAULT AS IDENTITY
                       PRIMARY KEY,
    source_customer_id BIGINT UNIQUE,
    customer_segment   VARCHAR(50),
    first_purchase_date DATE,
    last_purchase_date  DATE,
    created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- Unknown customer member.
-- Use customer_key = 0 when the source CustomerID is missing.

INSERT INTO dim_customer (
    customer_key,
    source_customer_id,
    customer_segment
)
VALUES (
    0,
    NULL,
    'Unknown'
)
ON CONFLICT (customer_key) DO NOTHING;


-- ============================================================
-- 3. DIMENSION: PRODUCT
-- ============================================================

CREATE TABLE IF NOT EXISTS dim_product (
    product_key       BIGINT GENERATED BY DEFAULT AS IDENTITY
                      PRIMARY KEY,
    source_stock_code VARCHAR(50) NOT NULL UNIQUE,
    product_name      TEXT,
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- ============================================================
-- 4. DIMENSION: COUNTRY
-- ============================================================

CREATE TABLE IF NOT EXISTS dim_country (
    country_key BIGINT GENERATED BY DEFAULT AS IDENTITY
                PRIMARY KEY,
    country_name VARCHAR(100) NOT NULL UNIQUE
);


-- ============================================================
-- 5. FACT: SALES TRANSACTION LINES
-- ============================================================

CREATE TABLE IF NOT EXISTS fact_sales (
    sales_key       BIGINT GENERATED BY DEFAULT AS IDENTITY
                    PRIMARY KEY,

    date_key        INTEGER NOT NULL,
    customer_key    BIGINT NOT NULL DEFAULT 0,
    product_key     BIGINT NOT NULL,
    country_key     BIGINT NOT NULL,

    invoice_no      VARCHAR(50) NOT NULL,
    transaction_type VARCHAR(20) NOT NULL,

    quantity        INTEGER NOT NULL,
    unit_price      NUMERIC(12, 4) NOT NULL,
    line_total      NUMERIC(14, 2) NOT NULL,

    loaded_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_sales_date
        FOREIGN KEY (date_key)
        REFERENCES dim_date(date_key),

    CONSTRAINT fk_sales_customer
        FOREIGN KEY (customer_key)
        REFERENCES dim_customer(customer_key),

    CONSTRAINT fk_sales_product
        FOREIGN KEY (product_key)
        REFERENCES dim_product(product_key),

    CONSTRAINT fk_sales_country
        FOREIGN KEY (country_key)
        REFERENCES dim_country(country_key),

    CONSTRAINT chk_sales_transaction_type
        CHECK (
            transaction_type IN (
                'SALE',
                'RETURN',
                'CANCELLATION'
            )
        )
);


-- ============================================================
-- 6. INDEXES FOR ANALYTICS QUERIES
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_fact_sales_date
    ON fact_sales(date_key);

CREATE INDEX IF NOT EXISTS idx_fact_sales_customer
    ON fact_sales(customer_key);

CREATE INDEX IF NOT EXISTS idx_fact_sales_product
    ON fact_sales(product_key);

CREATE INDEX IF NOT EXISTS idx_fact_sales_country
    ON fact_sales(country_key);

CREATE INDEX IF NOT EXISTS idx_fact_sales_invoice
    ON fact_sales(invoice_no);

CREATE INDEX IF NOT EXISTS idx_fact_sales_type
    ON fact_sales(transaction_type);


-- ============================================================
-- 7. ANALYTICS VIEW: NET SALES
-- ============================================================

CREATE OR REPLACE VIEW vw_sales_summary AS
SELECT
    d.year_number,
    d.year_month,
    c.country_name,
    p.source_stock_code,
    p.product_name,
    f.transaction_type,

    COUNT(*) AS transaction_lines,
    SUM(f.quantity) AS total_quantity,
    SUM(f.line_total) AS net_line_value

FROM fact_sales f

JOIN dim_date d
    ON f.date_key = d.date_key

JOIN dim_country c
    ON f.country_key = c.country_key

JOIN dim_product p
    ON f.product_key = p.product_key

GROUP BY
    d.year_number,
    d.year_month,
    c.country_name,
    p.source_stock_code,
    p.product_name,
    f.transaction_type;


COMMIT;


-- ============================================================
-- END OF RETAIL360 STAR SCHEMA
-- ============================================================
